"""CSV exports and the generated data dictionary."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from marketing_pipeline.creators.store import get_store

VIEWS = ("corpus", "customer", "research", "specialty-stats")

CORPUS_FIELDS = [
    ("handle", "TikTok handle, no @"),
    ("profile_url", "https://www.tiktok.com/@handle"),
    ("nickname", "Display name from profile HTML"),
    ("specialty_key", "Canonical GTM specialty key"),
    ("doctor_role", "doctor | consultant | gp | … from the insight card"),
    ("geo_country", "ISO country; GB for the customer lane"),
    ("follower_count", "Public follower count at last profile fetch"),
    ("posts_30d", "Videos in the hydrated window dated last 30 days"),
    ("median_views", "Median views on hydrated videos with a view count"),
    ("median_saves_per_1k", "Median saves per 1k views; research ranking signal"),
    ("median_shares_per_1k", "Median shares per 1k views"),
    ("median_engagement_rate", "Diagnostic (likes+comments+shares)/views; not the ranker"),
    ("private_practice", "True when practice_setting is private or mixed"),
    ("growth_intent_level", "0 none · 1 brand · 2 practice site · 3 explicit CTA"),
    ("positioning_line", "One-line L2 positioning from the insight card"),
    ("lane", "customer | research | both | discard | pending_review"),
    ("customer_score", "0–100; null components excluded"),
    ("research_score", "0–100; saves-weighted, not likes-only"),
    ("score_coverage", "Weight used / 100"),
    ("review_status", "pending | confirmed | rejected"),
    ("promoted", "True once promoted_at is set"),
    ("good_fit", "L3 auto-enqueue predicate"),
    ("deep_status", "none | queued | ingesting | ingested | brief_draft | brief_failed | brief_confirmed"),
    ("last_post_at", "Newest hydrated video timestamp"),
    ("scored_at", "When score_all last wrote this row"),
]

DICTIONARY_INTRO = """# Creator corpus data dictionary

Generated by `python -m marketing_pipeline creators export --view dictionary`.
Do not treat last-23/50 videos as growth history. Follower snapshots become a
growth signal only after two captures. Transcripts and captions are **not**
in these CSV views — they live on L3 packets / stored briefs.

Missing numeric inputs are **null**, never zero.
"""


def _lean_row(profile: dict[str, Any]) -> dict[str, Any]:
    setting = profile.get("practice_setting")
    return {
        "handle": profile.get("handle"),
        "profile_url": profile.get("profile_url"),
        "nickname": profile.get("nickname"),
        "specialty_key": profile.get("specialty_key"),
        "doctor_role": profile.get("doctor_role"),
        "geo_country": profile.get("geo_country"),
        "follower_count": profile.get("follower_count"),
        "posts_30d": profile.get("posts_30d"),
        "median_views": profile.get("median_views"),
        "median_saves_per_1k": profile.get("median_saves_per_1k"),
        "median_shares_per_1k": profile.get("median_shares_per_1k"),
        "median_engagement_rate": profile.get("median_engagement_rate"),
        "private_practice": setting in {"private", "mixed"},
        "growth_intent_level": profile.get("growth_intent_level"),
        "positioning_line": profile.get("positioning_line"),
        "lane": profile.get("lane"),
        "customer_score": profile.get("customer_score"),
        "research_score": profile.get("research_score"),
        "score_coverage": profile.get("score_coverage"),
        "review_status": profile.get("review_status"),
        "promoted": bool(profile.get("promoted_at")),
        "good_fit": profile.get("good_fit"),
        "deep_status": profile.get("deep_status"),
        "last_post_at": profile.get("last_post_at"),
        "scored_at": profile.get("scored_at"),
    }


def data_dictionary_markdown() -> str:
    lines = [DICTIONARY_INTRO, "", "## `creator_corpus_current` / CSV `corpus`", "", "| Field | Meaning |", "|---|---|"]
    for name, meaning in CORPUS_FIELDS:
        lines.append(f"| `{name}` | {meaning} |")
    lines.extend(
        [
            "",
            "## Other views",
            "",
            "| View | Filter |",
            "|---|---|",
            "| `customer` | lane in `customer`, `both`; same columns |",
            "| `research` | lane in `research`, `both`; same columns |",
            "| `specialty-stats` | `creator_specialty_stats` rows (exemplar **handles** only) |",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def write_data_dictionary(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(data_dictionary_markdown(), encoding="utf-8")
    return path


def _write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k) if row.get(k) is not None else "" for k in fieldnames})


def export_view(
    view: str,
    *,
    path: Path,
    store=None,
    dictionary_path: Path | None = None,
) -> dict[str, Any]:
    view = (view or "corpus").strip().lower()
    if view == "dictionary":
        dest = dictionary_path or path
        write_data_dictionary(dest)
        return {"view": "dictionary", "path": str(dest), "rows": 0}

    if view not in VIEWS:
        raise ValueError(f"unknown view {view!r}; expected {VIEWS} or dictionary")

    store = store or get_store()
    if view == "specialty-stats":
        rows = store.list("creator_specialty_stats")
        slim = []
        for row in rows:
            exemplars = row.get("exemplar_handles") or []
            if isinstance(exemplars, dict):
                names = exemplars.get("high_saves") or next(iter(exemplars.values()), [])
            else:
                names = exemplars
            if not isinstance(names, list):
                names = [names]
            slim.append(
                {
                    "specialty_key": row.get("specialty_key"),
                    "n_doctors": row.get("n_doctors"),
                    "exemplar_handles": ",".join(str(h) for h in names if h),
                }
            )
        _write_csv(path, ["specialty_key", "n_doctors", "exemplar_handles"], slim)
        return {"view": view, "path": str(path), "rows": len(slim)}

    profiles = store.list("creator_profiles")
    if view == "customer":
        profiles = [p for p in profiles if p.get("lane") in {"customer", "both"}]
    elif view == "research":
        profiles = [p for p in profiles if p.get("lane") in {"research", "both"}]
    rows = [_lean_row(p) for p in profiles]
    fields = [name for name, _ in CORPUS_FIELDS]
    _write_csv(path, fields, rows)
    return {"view": view, "path": str(path), "rows": len(rows)}
